spring:
  datasource:
    url: jdbc:h2:mem:maindb

  application:
    name: hw13

  sql:
    init:
      mode: always
      data-locations: classpath:data.sql
      schema-locations: classpath:schema.sql

  jpa:
    show-sql: true

    hibernate:
      ddl-auto: validate

    properties:
      hibernate:
        jdbc:
          batch_size: 10
        order_inserts: true

logging:
  level:
    org:
      springframework:
        security: DEBUG
app:
  init-users:
    enabled: true

server:
  port: 8000

